### ISSUE TITLE
fails to work with "No such file or directory"

### ISSUE THREAD

**Issue by tshepang** [Geemili/time-tracker#12]
I created a dir, linked in `~/.config/augr/config.toml`, but I get the following
> An error occured: Errors synchronizing data: [IOError { source: IOError { source: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }]

**Comment by raffomania** [comment]
You can make it work by creating  an empty `meta` folder inside your sync directory. The linked PR should fix this.
