### ISSUE TITLE
End Event?

### ISSUE THREAD

**Issue by memchk** [Geemili/time-tracker#8]
Is there a way to explicitly end an event? For example, if I do `augr start work`, can I do a `augr end work` and have the software track nothing?

My current strategy is to have a tag called "freetime" that I switch to anytime I don't want to be tracking my time. However, this greatly clutters the summary.

I would be happy to implement this feature if its wanted, if not, I would suggest adding to the Guide a canonical way of handling untracked / free time, as this confused me when first reading it, which again I would be happy to do.

**Comment by leroycep** [comment]
The canonical way of tracking nothing is to start with no tags:

```
$ augr start
e05678b4-0cf7-4a81-9038-635c5c3bd38f
$ augr
Date  Start Duration Total     Tags
――――― ――――― ―――――――― ――――――――  ――――――――
09/16 05:14 27m      27m      
```
And yes, this should definitely be in the guide! It's an oversight on my part that this is not mentioned. Thanks for making the issue.

I also want to mention that tracking nothing is treated like every other instance of tracking something, except when using `augr chart`. To `augr summary` it is merely another event, albeit one with no tags. If you track 'nothing' it shows up as a blank spot on the chart:

```
$ augr chart
Day 0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 
Tue ████████████████  █████████████████████████████████████████  ███████████
Wed ████████████████ █████████████████████ ███████████████     ██   ████████
Thu ████████████████    ██ ██████████████████████                           
Fri ████████████████     ███████████████████████████ ███████████████████████
Sat ███████████████████████████████       ████  ████████████████████████████
Sun ████████████████████████████         ███      ██████████████    ████████
Mon ████████████████  ██████████████████████████████████████                
```

**Comment by memchk** [comment]
Thank you! I have been using augr since you made your optimization post on /r/rust, its been a great tool!
